### ISSUE TITLE
Window position is noise?

### ISSUE THREAD

**Issue by slestak** [timabell/msaccess-vcs-integration#109]
Has there been any discussion regarding is window position should be recorded? I am a new user and that is the first hurdle I am working on with my small team. Maybe that could be an option in the export config?

Here is an example from a diff we were discussing.

 Begin
     State =0
     Left =0
     Top =0
-    Right =1305
+    Right =1627
     Bottom =953
     Left =-1
     Top =-1
-    Right =1289
-    Bottom =228
+    Right =1611
+    Bottom =92
     Left =0
     Top =0
     ColumnsShown =651
@@ -152,7 +157,7 @@ Begin
         Left =455
         Top =5
         Right =630
-        Bottom =113
+        Bottom =141
         Top =0
         Name ="WorkOrders"
         Name =""

**Comment by hecon5** [comment]
Try out the Joyfull service fork; it's much more active. 
https://github.com/joyfullservice/msaccess-vcs-integration

That said, the window position is based on pips, which is a wholly different item, and will induce noise based on your resolution and / or other factors. 

Depending on how you develop, your team may determine a better way would be to just export and discard those changes in git.

**Comment by slestak** [comment]
Oh, I apologize. I am using that fork. I will raise the issue over there. I had considered that this might have been implemented on one of the many forks. Closing this here.  Thanks.
