### ISSUE TITLE
variable name capitalisation being changed - vba editor issue

### ISSUE THREAD

**Issue by CrispinF** [timabell/msaccess-vcs-integration#11]
We have noticed that sometimes doing ExportAllSource results in huge numbers of commits, with the apparent change being along these lines:
-On Error GoTo Err_Form_Open
+On Error GoTo err_Form_Open
or 
-If Me!PerUID.oldValue > "" And Me!PerUID.oldValue <> ...
+If Me!PerUID.OldValue > "" And Me!PerUID.OldValue <> ...
This does not happen every time, but when it does, our repo is flooded with spurious commits.
At first sight I can't see why this is happening - in both the above cases it is hard to see how the file could genuinely have been in the previous state (e.g. .oldValue is always instantly converted to .OldValue on entry). And we know that all/most of the files showing changes have not been edited by a human since the previous export. 
Any ideas?  Will post if we find the cause.

**Comment by jwbrookes** [comment]
Ah! The joys of vba. I'm afraid this is one of vba's 'features'.

The vba editor will automatically change variable names to have the same capitalisation as the variable definition. Unfortunately the editor has no concept of variable type or scope. Instead it just looks for variable calls that have the same name as a definition and then applies that definitions' capitalisation. This means that if you put two variable definitions of the same name in different parts of the program and with different capitalisation, the editor will simply take the most recent definition and impose its capitalisation on any variable calls or definitions with that name.

For example:
In a form sub-routine define a variable with the first char in a lower case
`Private Sub Form_Current()`
`Dim oLdValue as AccessObject`
Then add in a line to test the value of your form control
`If Me!PerUID.OldValue Then`
Notice how the line changes to:
`If Me!PerUID.oLdValue Then`
To finish our example add in this line
`Dim OLDvalue As Integer`
Notice how the capitalisation changed even in the previous definition.

As I said, the vba editor has no concept of type or __scope__. So even if `Dim oLdValue as AccessObject` or `Dim OLDvalue As Integer` were put into a different sub it would still change the capitalisation of `Me!PerUID.OldValue`.

So to answer your question - the files haven't been edited by a human, they have been edited by the vba editor!

The only way around this is to stick to a capitalisation style throughout.

**Comment by CrispinF** [comment]
Good point. What surprised me was it has affected Access properties (.OldValue) as well as our own. Probably best to avoid creating variables with names the same as Access properties. Certainly one to watch out for, but actually the VCS export may help highlight and avoid this.
