### ISSUE TITLE
Possible optimization using MSysObjects

### ISSUE THREAD

**Issue by rikbosch** [timabell/msaccess-vcs-integration#14]
Hi, we have a rather large MDB application, importing and exporting the changes takes a long time (about 15-25 minutes).

Would it be feasible to check the DateUpdate column in MSysObjects table and export only those objects that have changed since the last export (or commit)?

**Comment by Ronaldvr** [comment]
It is useless to do this via MSysObjects, since that does not reliably update the timestamp of an update.

**Comment by timabell** [comment]
That seems like a no then, I'll close this until new information comes to light.
