### ISSUE TITLE
Rubberduck integration?

### ISSUE THREAD

**Issue by Ronaldvr** [timabell/msaccess-vcs-integration#17]
In my search for a cvs I came across this project but also I found RubberDuck here: https://github.com/rubberduck-vba/Rubberduck/wiki

Both are actually incomplete: this project allows all components to be under source countrol, but rubberduck has better integration with git.

It could be an idea to use both apporaches to (initially?) create a rubberduck -accessvcs integartion fork?

**Comment by jwbrookes** [comment]
Yes and no. Rubberduck appears to be an extension of the vba editor, not something aimed at just access. I suspect that access objects are beyond the scope of the editor, so extending rubberduck will not be possible. I will check with the devs just to be sure.

However I could use the same method as rubberduck for this project - create an add-on for access. That would also mean we could avoid using vba...

**Comment by timabell** [comment]
closing this issue as it's not a specific thing to do; that doesn't mean I disapprove though, just keeping the issue list tidy.

**Comment by ckuhn203** [comment]
@Ronaldvr what components aren't we exporting? Please open an issue on our repo and we'll see what we can do to support it. https://github.com/rubberduck-vba/Rubberduck/issues

**Comment by retailcoder** [comment]
@ckuhn203 the queries, table definitions, etc. - the actual Access-specific stuff that isn't specifically VBA but that's definitely worth having under source control.

**Comment by retailcoder** [comment]
@jwbrookes we are currently finalizing source control integration for the release of Rubberduck 2.0; at this point we aren't including anything host-specific (i.e. requiring anything other than the VBIDE API), but 2.x might actually see that kind of feature - extending Rubberduck to support it is definitely possible, and we'll happily take a PR that translates your hard work to C# - if you have a Code Review Stack Exchange account, come have a chat in our "war room": http://chat.stackexchange.com/rooms/14929/vba-rubberducking
