### ISSUE TITLE
Initial Import Stops

### ISSUE THREAD

**Issue by dgulliver** [timabell/msaccess-vcs-integration#19]
Hi Tim,

Followed readme but when I do ExportAllSource its stops after exporting forms. I see it calls SanitizeTextFiles after the form count is displayed but it just stops. When I ctrl+break the code I DoEvent is highlighted in yellow but I cannot step over/into.
Code window says running in title bar.

Any advice?

Regards,
Darren

**Comment by jwbrookes** [comment]
Comment out the DoEvents command. It's a win3.1 multithreading command (time sharing). It works by handing over the thread to the system , so you can't stop execution.

**Comment by dgulliver** [comment]
I tihnk it's me being impatient, I have 5 forms that are 10mb, 4 that are 6mb, 8 forms that are 4mb so this will take sometime to sanitise. Thank you JW ro responding though.
