### ISSUE TITLE
DeleteFile function

### ISSUE THREAD

**Issue by jwbrookes** [timabell/msaccess-vcs-integration#2]
This isn't being used (it's commented out). 
@timabell Do you want to keep this or can it be deleted?

**Comment by timabell** [comment]
kill it :-) I'm not a fan of commented out code, that's generally what source control history is for. By the way don't feel you have to ask, just go ahead and do as you see fit with the whole thing. If I were less keen on anything (which looks unlikely so far) I can always branch off an older version and start a discussion then.
