### ISSUE TITLE
Decimal types are exported as VARCHAR

### ISSUE THREAD

**Issue by mgrojo** [timabell/msaccess-vcs-integration#26]
With the current version, when exporting decimal types, they are converted to VARCHAR without size. This is due to the function VCS_Table.strType returning VARCHAR in the Else branch.

I have a solution for this, but it has a drawback: for extracting the Precision and NumericScale we have to use another library in the references: Microsoft ADO Ext. 2.x for DLL and Security. See https://social.msdn.microsoft.com/Forums/office/en-US/883087ba-2c25-4571-bd3c-706061466a11/how-can-i-programmatically-access-scale-property-of-a-decimal-data-type-field?forum=accessdev

I don't know wether that would be a problem.

Another change should be done in the import in order to recognize the DECIMAL field in the SQL. One must use ADODB.Connection for the Execute of the SQL. This is working for me as far as the references problem is reached (Issue #16). 

I don't know if both changes are problematic or not. Would this be accepted in the project? I can make a pull request if you want to see the code.

**Comment by timabell** [comment]
Happy to have a look at pull requests for these changes. I'll have to trust your judgement on these changes so make sure you think it's ready for inclusion, if it looks reasonable I'll merge and we'll see if we get any feedback from others over time.
