### ISSUE TITLE
Next Steps

### ISSUE THREAD

**Issue by jwbrookes** [timabell/msaccess-vcs-integration#3]
This is the general plan for what will be done to the project next.

 1. Fix bugs in current version
 2. Release version
 3. Refactor current version, seperating each responsibility into its own module
     - eg Functions to handle tables put into their own module
     - Will need to add a module to load in other modules or compile the modules together for each release
 4. Add in missing features
     - Data Macro Import/Export
     - Linked table Import/Export (Link definition)
     - Table relationships Import/Export (This is only available for normal tables in the current version)
 5. Release version
 6. Rework & improve existing features

**Comment by timabell** [comment]
Sounds good to me :-)

**Comment by vais** [comment]
@timabell @jwbrookes does this work for Access 2002? I cannot seem to get around the checksum issue. Simply removing the `Checksum =` line does not work, `LoadFromText` still fails. Any suggestions?

**Comment by timabell** [comment]
@vais does what work?

**Comment by vais** [comment]
Sorry, @timabell, I was not being clear. I meant does msaccess-vcs-integration work for Access 2002 mdb files? I have my own home-grown solution for exporting and importing forms as text, but I cannot get around the issue of checksums, which makes it impossible to branch and merge changes to forms, since the modified text file will no longer have a valid checksum. I was wandering if/how msaccess-vcs-integration solves that problem. Thanks again for your reply!

**Comment by timabell** [comment]
Oh I see, I suspect not as I've only run it on 2012, but feel free to raise specific bugs if you find compatibility issues. It might make sense to fork the project for legacy support. I did try running it on 2000 (don't ask) but unsurprisingly it didn't work. Whether I put time into supporting this project further depends on what work I end up doing in the future, but I tend to avoid access if I can! It's up to @jwbrookes what they want to do towards this.

**Comment by vais** [comment]
Thanks, @timabell, appreciate the quick response!

**Comment by jwbrookes** [comment]
Removing the `Checksum =` line in 2010/2012 doesn't have any effect on the `LoadFromText` function. I'm guessing that this is a problem with previous versions of Access. I don't have any previous versions to hand so I can't verify this. As this is not a problem in Access 2010/2012 there is no workaround or solution for it.

**Comment by vais** [comment]
Thank you @jwbrookes.

**Comment by timabell** [comment]
If you still want this info it should probably move to the [wiki](https://github.com/timabell/msaccess-vcs-integration/wiki) or something now.
