### ISSUE TITLE
Table name with "/" in name

### ISSUE THREAD

**Issue by aricbeaver** [timabell/msaccess-vcs-integration#49]
If a table name has a "/" in the name, for example, "Table/Name" the export will fail on Line 124 in VCS_Table

`Set OutFile = FSO.CreateTextFile(fileName, overwrite:=True, Unicode:=False)`

**Comment by aricbeaver** [comment]
Oops, sorry. Didn't see the other open issue discussing this.

**Comment by timabell** [comment]
#40
