### ISSUE TITLE
creates blank xml files on *import*

### ISSUE THREAD

**Issue by timabell** [timabell/msaccess-vcs-integration#6]
very odd, ran out of time debugging this, it's something to to do with the ImportObject() function in IE_Functions 

https://github.com/timabell/msaccess-vcs-integration/blob/master/MSAccess-VCS/VCS_IE_Functions.bas#L30

eg  `msaccess-vcs-integration\demo\source\tbldef\color_lookup.xml`

**Comment by jwbrookes** [comment]
The blank .xml file is for the table data macros. 

The call to ImportObject() is being made from VCS_DataMacro.ImportDataMacros() , which is being called from VCS_Table.ImportTableDef()

ImportObject() is probably trying to manipulate a file that doesn't exist, thereby creating it.

The ImportDataMacros() call should be moved into ImportAllSource() or a file check added somewhere in the ImportDataMacros() sub.

I'll take a look into this sometime late next week.

**Comment by timabell** [comment]
nice one
