### ISSUE TITLE
Error 2950 "Reservated Error" on ExportAllSource

### ISSUE THREAD

**Issue by gsasoftware** [timabell/msaccess-vcs-integration#7]
Error 2950 "Reservated Error" on ExportAllSource in modules.
I think the module name is Módulo Validación NIF/IBAN. maybe is the erro?

**Comment by timabell** [comment]
No idea what that could be. Any more details you can provide to help troubleshoot would be welcomed.

I found a suggestion that it could be just a compilation screw-up by access - http://answers.microsoft.com/en-us/office/forum/office_2010-access/run-time-error-2950-reserved-error/f8bdd0d9-3154-42b4-af0b-6d86007c4468

Other random thing: http://www.tek-tips.com/viewthread.cfm?qid=1646420

**Comment by gsasoftware** [comment]
It is the module name. thanks.

**Comment by timabell** [comment]
Excellent :-) Any more details you could provide to help others with the same issue would be appreciated, such as how you figured out what it was, what exactly broke, and how you fixed it. Cheers.
