### ISSUE TITLE
reimporting reseting tables

### ISSUE THREAD

**Issue by lastlink** [timabell/msaccess-vcs-integration#70]
I don't know if I misunderstood the documentation, but when I run the import it deletes any information in the tables, is there a way to disable this default behavior?

**Comment by lastlink** [comment]
My [pr](https://github.com/timabell/msaccess-vcs-integration/pull/71) recently solved this issue when using the buttons for importing exporting the forms it ignores the data import/export functions completely using an optional parameter.

**Comment by timabell** [comment]
Cool, shall we close this issue?

**Comment by lastlink** [comment]
Should be fine.
