### ISSUE TITLE
Escaping/unescaping of table data - backslashes

### ISSUE THREAD

**Issue by MarianAldenhoevel** [timabell/msaccess-vcs-integration#83]
My Project includes a table that holds pathnames and one of those happens to look like "...db\test...".

When exporting this the backslash rightly gets escaped to a double backslash. But when importing the data back in the unescaping breaks it by reading the remaining "\t" as a tab and converting that.

I have added a very slightly cleverer unescape routine to my copy which fixes the problem for me.

Find attached VCS_Table.bas which calls VCS_EscapeString and VCS_UnescapeString respectively instead of the simple string replacement. And VCS_IE_Functions.bas which implements the pair near the bottom.

VBA is not my first language, so I do not claim any nice properties of this implementation other than that it works for me.

Thank you very much for your work, it has made developing with MS-Access much more bearable for me :-).

Marian

**Comment by MarianAldenhoevel** [comment]
[VCS_Escape.zip](https://github.com/timabell/msaccess-vcs-integration/files/2786498/VCS_Escape.zip)

**Comment by MarianAldenhoevel** [comment]
[VCS_Escape.zip](https://github.com/timabell/msaccess-vcs-integration/files/2786503/VCS_Escape.zip)

**Comment by timabell** [comment]
would you be able to turn this into a pull request? more likely to get included that way
glad you found it useful

**Comment by MarianAldenhoevel** [comment]
I don't really know how to do that.

I will take this as an opportunity to learn, but it's rather low on my priority list at the moment.

**Comment by timabell** [comment]
You can leave the issue open, it's a valid problem

**Comment by timabell** [comment]
fixed in #93
