### ISSUE TITLE
ExportAllSource Stalls Access after 30 minutes 

### ISSUE THREAD

**Issue by envisionnw** [timabell/msaccess-vcs-integration#9]
First, many thanks for this *excellent* tool! It does exactly what we need it to and has been working great for most of our Access databases. 

Unfortunately I have one database that has a large number of forms and queries, that has stalled out and crashed Access each time I've run the command. It's successful for some forms and I'm not seeing an error, just a long churning process which fails after about 30 minutes.

One thing I've considered is trying to "chunk" the export by type, although I'm thinking this is more an issue of large numbers of forms (~60) so type wouldn't handle it as much as only exporting a certain number of forms, reports, queries, etc. at a time.

Any suggestions on how to get past the stall?  I'm thinking perhaps its a tweak to ExportAllSource to comment out a certain type or something similar. Perhaps others have experienced a similar roadblock where they are unable to fully get through the export?

Thanks again for any/all recommendations.

**Comment by timabell** [comment]
pass I'm afraid

**Comment by jwbrookes** [comment]
I don't think this has anything to do with the large number of forms. Sounds more like a bug in the form export code. Have you tried exporting just the form that the export fails on? Forms are exported in alphabetical order, so the form after the last one that was successful exported will be the one that is causing the issue.
Also what version of Access are you using?

**Comment by timabell** [comment]
closing as the requested info wasn't supplied

**Comment by envisionnw** [comment]
Sorry for the late reply, the Access version is 2010. I probably won't get back to that particular database for a while, but hope to use the ExportAllSource for it. From the last iteration a few weeks ago it was failing on a rather complex form with subforms and tabs. Other forms with subforms were fine. Workaround I think would be to case the code for that particular form, then manually export it separately (if possible).
